---
title: "451 Sample"
author: "Micah Jona"
date: "11/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(xgboost)
library(tidyverse)
library(caret)
library(fastDummies)
library(tidymodels)
library(magrittr)
library(lme4)
library(tictoc)
library(baseballr)
```


Data pre-processing.
```{r}
# reading in data
pitches_2019 <- read_csv("project_data.csv")

# getting rid of columns that the model won't need. 
pitches_2019 %<>% 
  select(-c("spin_dir", "spin_rate_deprecated", "break_angle_deprecated", "break_length_deprecated", "game_type", "type",
            "hit_location", "bb_type", "game_year", "hc_x", "hc_y", "tfs_deprecated", "tfs_zulu_deprecated", "umpire", "sv_id",
            "fielder_2", "hit_distance_sc", "launch_speed", "launch_angle", "pitcher_1", "fielder_3", "fielder_4", "fielder_5",
            "fielder_6", "fielder_7", "fielder_8", "fielder_9", "estimated_ba_using_speedangle", "estimated_woba_using_speedangle",
            "woba_value", "woba_denom", "babip_value", "iso_value", "launch_speed_angle", "at_bat_number", "pitch_number",
            "pitch_name", "home_score", "away_score", "bat_score", "fld_score", "post_away_score", "post_home_score",
            "post_bat_score", "post_fld_score", "if_fielding_alignment", "of_fielding_alignment", "barrel", "pitcher", "batter",
            "events", "des", "home_team", "away_team"))

# for catcher framing only need pitches called by umpire (called strikes, balls (including blocked balls))
pitches_2019 <- pitches_2019 %>%
  filter(description == "called_strike" | description == "blocked_ball" | description == "ball")

# turn on_3b/2b/1b into binary (yes/no) 
pitches_2019 <- pitches_2019 %>%
  mutate(on_3b_yes_no = ifelse(is.na(on_3b), 0, 1)) %>%
  mutate(on_2b_yes_no = ifelse(is.na(on_2b), 0, 1)) %>%
  mutate(on_1b_yes_no = ifelse(is.na(on_1b), 0, 1)) %>%
  select(-c("on_3b", "on_2b", "on_1b"))

# remove pitch_type: KN, "", EP, FO. and make KC = CU
pitches_2019$pitch_type[pitches_2019$pitch_type == 'KC'] <- 'CU'

pitches_2019 <- pitches_2019[!(pitches_2019$pitch_type =="KN"  | 
                         pitches_2019$pitch_type =="" |
                         pitches_2019$pitch_type =="EP" |
                         pitches_2019$pitch_type =="FO"),]

# turn description (called strike/ball) into binary (yes/no)
pitches_2019 <- pitches_2019 %>%
  mutate(is_strike = ifelse(description == "called_strike", 1, 0)) %>%
  select(-c("description"))

# player look up by mlbam key
chadiwck_reduced <- chadwick_player_lu_table %>% select (key_mlbam, name_last, name_first)
# remove NA to make df smaller
chadiwck_reduced <- chadiwck_reduced[!is.na(chadiwck_reduced$key_mlbam),]
# getting each catcher's name
pitches_2019 <- merge(x = pitches_2019, y = chadiwck_reduced, by.x = "fielder_2_1", by.y = "key_mlbam")
pitches_2019 <- mutate(pitches_2019, catcher_name = paste(name_first, name_last, sep = " "))
pitches_2019 <- subset(pitches_2019, select = -c(name_last, name_first))

#can now remove fielder_2 b/c we have catcher name
pitches_2019 <- pitches_2019 %>%
  select(-c("fielder_2_1"))

#umpires
umpire_ids_game_pk <- read_csv("umpires_ids_game_pk.csv")
names(umpire_ids_game_pk) = c("id", "position", "umpire_name", "game_pk", "game_date")
hp_umpires <- umpire_ids_game_pk %>%
  filter(position == "HP") %>%
  filter(game_date < "2019-9-30" & game_date > "2019-03-22") %>%
  select(c("game_pk", "umpire_name"))

pitches_2019 <- merge(pitches_2019, hp_umpires, by = c("game_pk"))
pitches_2019 %<>% select(-c("game_pk"))
#nrow(pitches_2019) = 380841 before umps
#nrow(pitches_2019) = 378517 - after umps 

pitches_2019 %<>% 
  mutate(batter_name = player_name) %>%
  select(-c("player_name"))

# turning strings into factors
pitches_2019 %<>%
  mutate(pitch_type = as.factor(pitch_type)) %>%
  mutate(batter_name = as.factor(batter_name)) %>%
  mutate(stand = as.factor(stand)) %>%
  mutate(p_throws = as.factor(p_throws)) %>%
  mutate(balls = as.factor(balls)) %>%
  mutate(strikes = as.factor(strikes)) %>%
  mutate(outs_when_up = as.factor(outs_when_up)) %>%
  mutate(inning = as.factor(inning)) %>%
  mutate(inning_topbot = as.factor(inning_topbot)) %>%
  mutate(pitcher_name = as.factor(pitcher_name)) %>%
  mutate(catcher_name = as.factor(catcher_name)) %>%
  mutate(umpire_name = as.factor(umpire_name))

# turning pitch type variable into dummy variables 
pitches_2019 <- fastDummies::dummy_cols(pitches_2019,select_columns = c("pitch_type")) 
```


No context xgboost model. Meaning only focusing on statcast pitch characteristics (no count, base-runners, etc). 
```{r}
# set seed for reproducibility -------------------------------------------
set.seed(69)

# create indecies for splitting (need to use a specific column from df for it to run)
train_index <- createDataPartition(y = pitches_2019$is_strike, p = .7, list = FALSE) %>% as.vector()

# split into train and test
train <- pitches_2019[train_index,]
test <- pitches_2019[-train_index,]

vec_label_train <- train$is_strike
train_data <- as.matrix(train %>% select(-c("game_date", "zone", "pitcher_name", "is_strike", "catcher_name", "umpire_name", "batter_name", "pitch_type",  "stand", "p_throws", "balls", "strikes","outs_when_up", "inning", "inning_topbot", "on_3b_yes_no", "on_2b_yes_no", "on_1b_yes_no"))) #gonna deselect catcher/pitcher/batter_name/game_date here too

vec_label_test <- test$is_strike
test_data <- as.matrix(test %>% select(-c("game_date", "zone", "pitcher_name", "is_strike", "catcher_name", "umpire_name", "batter_name", "pitch_type", "stand", "p_throws", "balls", "strikes", "outs_when_up", "inning", "inning_topbot", "on_3b_yes_no", "on_2b_yes_no", "on_1b_yes_no"))) #gonna deselect catcher/pitcher/batter_name/game_date here too

# convert the train and test into xgb.DMatrix
# using model.matrix will handle converting factors to dummy columns
x_train = xgb.DMatrix(data = train_data, label = vec_label_train)
x_test = xgb.DMatrix(data = test_data, label = vec_label_test)


vec_label_all <- pitches_2019$is_strike
train_all <- as.matrix(pitches_2019 %>% select(-c("game_date", "zone", "pitcher_name", "is_strike", "catcher_name", "umpire_name", "batter_name", "pitch_type", "stand", "p_throws", "balls", "strikes", "outs_when_up", "inning", "inning_topbot", "on_3b_yes_no", "on_2b_yes_no", "on_1b_yes_no"))) #gonna deselect catcher/pitcher/batter_name/game_date here too

full_train = xgb.DMatrix(data = train_all, label = vec_label_all)


# Using the xgboost package and cv method built in, test different parameters -----------

params <-
  list(
    booster = "gbtree",
    objective = "binary:logistic",
    eta = 0.15,
    gamma = 14,
    max_depth = 7,
    min_child_weight = 1,
    subsample = 1,
    colsample_bytree = 1,
    base_score = mean(pitches_2019$is_strike),
    nthread = 0
  )
set.seed(69)
tic()
xgb_cv <-xgboost::xgb.cv(params = params, data = x_train, nrounds = 150, nfold = 5, showsd = T, stratified = T, print_every_n = 1, early_stopping_rounds = 20)
time_took <- toc()
print(time_took)


# which round was lowest best iteration from
nrounds <- xgb_cv$best_iteration

# train model with that number of rounds
set.seed(69)
tic()
xgb_mod <- xgboost::xgboost(params = params, data = x_train, nrounds = nrounds, verbose = 2)
time_took <- toc()
print(time_took)


# plot importance of variables
importance <- xgb.importance(feature_names = colnames(xgb_mod), model = xgb_mod)

importance

importance_plot <- xgb.ggplot.importance(importance_matrix = importance)

importance_plot

# make prediction with model
xgb_mod_pred <- predict(xgb_mod, x_test)

# add predictions to test data
test$pred <- xgb_mod_pred

# find abs and sq error
test <- test %>%
  mutate(error = is_strike - pred)

test %>% summarise(mean_abs_error = mean(abs(error)),
                   mean_sq_error = mean(error^2),
                   root_mean_sq_error = sqrt(mean(error^2)))

# Train on All Data ---------
set.seed(69)
tic()
xgb_mod_full <- xgboost::xgboost(params = params, data = full_train, nrounds = nrounds, verbose = 2)
time_took <- toc()
print(time_took)


# make prediction
xgb_mod_full_pred <- predict(xgb_mod_full, full_train)

# add predictions to all the data
full_pred_data <- data.frame("is_strike" = pitches_2019$is_strike, "pred" = xgb_mod_full_pred)

# find abs and sq error
full_pred_data <- full_pred_data %>%
  mutate(error = is_strike - pred)

full_pred_data %>% summarise(mean_abs_error = mean(abs(error)),
                   mean_sq_error = mean(error^2),
                   root_mean_sq_error = sqrt(mean(error^2)))
```



```{r}
pitches_2019$is_strike_pred <- xgb_mod_full_pred

pitches_2019_me_model <- pitches_2019 %>% 
  select(c("is_strike", "is_strike_pred", "inning_topbot", "catcher_name", "pitcher_name", "umpire_name", "batter_name"))

tic()
testing_glmer <- glmer(is_strike ~ is_strike_pred + inning_topbot + (1|catcher_name) + (1|pitcher_name) + (1|umpire_name) + (1|batter_name) + (1|catcher_name:is_strike_pred), data = pitches_2019_me_model, family=binomial(link = "probit"), nAGQ = 0)
toc()

glmer_is_strike_pred <- predict(testing_glmer, type = "response")

pitches_2019$glmer_is_strike_pred <- glmer_is_strike_pred
```